name = "Funky Hardcore MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae892bffef2d81b4e7664bf3067465c7ddd8e5fd8acf708e6dd30efdc90181a4"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
