name = "Funky Hardcore MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08b7b33ac1fd4bac30e1be24060ccf5fed3e95b4e0c974847e34966d4b5e0604"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
