name = "Funky Hardcore MC"
author = "FunkyChickenMC"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f422beb29be5711f46c8a36a4a0d901944eecca14b859fb06c069b6353c2a06"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
